print("Enter 3 items for your shopping list")
item1 = input("Enter item1: ")
item2 = input("Enter item2: ")
item3 = input("Enter item3: ")
Shoppinglist = (item1, item2, item3)
lst = list(Shoppinglist)
print("Enter 2 more items:")
item4 = input("Enter item4: ")
item5 = input("Enter item 5: ")
lst.append(item4)
lst.append(item5)
print(lst)
shopplst = tuple(lst)
print(shopplst)
joinedSL = "|".join(shopplst) 
print(joinedSL)